name: proyectofinal
description: "A new Flutter project."
publish_to: 'none'

# Version
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2 # Dependencia para el acceso a la cámara
  http: ^1.2.2
  async: ^2.11.0
  # Si usas Google Cloud Vision, también puedes agregar esta dependencia:
  googleapis: ^13.2.0
  googleapis_auth: ^1.3.0
  flutter_dotenv: ^5.2.1
  geolocator: ^10.0.0
  flutter_gemini: ^2.0.5
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  # iOS style icons para un diseño Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.jpg
    - assets/texture.png

